version: "3.7"
services:
  frontend:
    image: public.ecr.aws/b4h5r6n2/basicwebapp:0.0.0
    environment:
      SERVER_LINK: "0.0.0.0:8080"
    ports:
      - "8000:8000"
  backend:
    image: public.ecr.aws/b4h5r6n2/resnet_cpu:0.0.0
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      BATCH_SIZE: 1
      LINGER_MS: 5
      WORKERS: 2
      GPUS: 0
